# Usery OS Pacman Configuration

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR (for Calamares installer)
[chaotic-aur]
Include = pacman.d/chaotic-mirrorlist

# Usery OS Custom Package Repository
[usery]
SigLevel = Optional TrustAll
Server = https://samarofficals.github.io/jolly-darwin/x86_64
