# Usery OS Pacman Configuration

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS Repository (for Calamares installer)
[cachyos]
SigLevel = Never
Server = https://mirror.cachyos.org/repo/x86_64/cachyos
# Usery OS Custom Package Repository
[usery]
SigLevel = Optional TrustAll
Server = https://samarofficals.github.io/jolly-darwin/x86_64
