# Calamares Settings for Usery OS
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id:       packages
    module:   packages
    config:   packages.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - packages@packages
    - umount
  - show:
    - finished

brand-image: "/usr/share/backgrounds/usery/usery_wallpaper.png"
style-sidebar-background: "#1a1b26"
style-sidebar-text: "#ffffff"

show-back-on-welcome-page: false
show-cant-exit-after-write: true
