# Kitty Terminal Configuration
font_family      Noto Sans Mono
font_size        11.0

# Window customization
background_opacity 0.85
dynamic_background_opacity yes

# Colors
background #1a1b26
foreground #a9b1d6

# Curser
cursor #c0caf5
cursor_shape block

# Mouse behavior
detect_urls yes

# Performance / Settings
enable_audio_bell no
window_padding_width 10
confirm_os_window_close 0
